import { JSDOM, VirtualConsole } from 'jsdom';
import fs from 'node:fs';
const vc = new VirtualConsole();
const errors = [];
vc.on('jsdomError', e => errors.push(e.message || String(e)));
const dom = new JSDOM(fs.readFileSync('index.html', 'utf8'), { runScripts: 'dangerously', pretendToBeVisual: true, virtualConsole: vc, url: 'https://x/' });
await new Promise(r => setTimeout(r, 1500));
const root = dom.window.document.getElementById('root');
console.log('Children:', root?.children.length, '| HTML len:', root?.innerHTML?.length, '| Errors:', errors.length);
errors.slice(0,3).forEach(e => console.log('-', e.slice(0,300)));
